name: Build
on:
  pull_request:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: miwoli/jugger/.github/workflows/setup.yml@v1
      - name: Build
        run: lerna run build