name: Checks
on:
  pull_request:
jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml
  build:
    needs: setup
    uses: ./.github/workflows/build.yml