name: Linter
on: 
  pull_request:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: miwoli/jugger/.github/workflows/setup.yml@v1
      - name: Lint
        run: eslint .
